name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore
        run: dotnet restore FluentRetry.sln
      - name: Build
        run: dotnet build FluentRetry.sln -c Release --no-restore
      - name: Test
        run: dotnet test FluentRetry.Tests/FluentRetry.Tests.csproj -c Release --no-build --verbosity minimal
